spring:
  application:
    name: rent-a-car

  datasource:
    url: jdbc:mysql://localhost:13306/rent-a-car?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    web: DEBUG
    org:
      springframework:
        web: DEBUG
        boot:
          autoconfigure:
            jdbc: DEBUG



application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
